language: node_js
node_js: '8'


script:
  - yarn build
  - yarn build-website

before_deploy:
  - cd docs
  - npm install
  - npm run build
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ./docs/dist
  on:
    branch: master
