language: node_js
node_js: '10'

cache: yarn

install: yarn

stages:
  - name: npm release
    if: branch = master

jobs:
  include:
    - stage: npm release
      script: yarn run generate
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
