language: node_js
node_js: '10'

cache: yarn

install: yarn

stages:
  - Docs
  - Release   

jobs:
 include:
    - stage: Release
      name: "Releasing a new version"
      if: tag IS present
      script: yarn run generate
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+

    - stage: Docs
      name: "Building Docs"
      if: branch = master
      script: yarn run generate && yarn run docz:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: docs
        target_branch: gh-pages
        on:
          branch: master
