language: node_js
node_js: '10'

cache: yarn

install: yarn
script:
  - yarn run generate

jobs:
  include:
    - stage: build Docs
      script:
        - yarn run generate
        - yarn run docz:build

    - stage: npm release
      if: tag IS present
      script: yarn run generate
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
